import Head from "next/head";
import Image from "next/image";
import Navbar from "../../components/navbar/navbar";
import Footer from "../../components/footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>SRM INTERACTION PORTAL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Navbar />

        <Footer />
      </main>
    </>
  );
}
